-----------------------------------
---------instead of trigger--------
-----------------------------------

CREATE VIEW EMP_DETAILS_VIEW AS
SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, D.DNAME, D.LOC FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO

ALTER TRIGGER TRIGGER_EMP_DETAILS_DML
ON EMP_DETAILS_VIEW
INSTEAD OF INSERT
AS
BEGIN
	DECLARE @MAX INT, @DEPT VARCHAR(20), @DEPTNO INT
	SELECT @DEPT = DNAME FROM INSERTED 
	IF @DEPT IS NULL
	BEGIN
		RAISERROR('DEPT VALE NOT PROVIDED',16,0)
	END
	ELSE
	BEGIN
		SELECT @DEPTNO=DEPTNO FROM DEPT WHERE DNAME = @DEPT
		
		IF @DEPTNO IS NULL
		BEGIN
			SELECT @MAX = MAX(DEPTNO) +10 FROM DEPT
			INSERT INTO DEPT(DEPTNO,DNAME,LOC)
			SELECT @MAX,I.DNAME,I.LOC FROM INSERTED I
	
			INSERT INTO EMP(EMPNO,ENAME,JOB,SAL,DEPTNO)
			SELECT I.EMPNO,I.ENAME,I.JOB,I.SAL,@MAX FROM INSERTED I
		END
		ELSE
		BEGIN
			INSERT INTO EMP(EMPNO,ENAME,JOB,SAL,DEPTNO)
			SELECT I.EMPNO,I.ENAME,I.JOB,I.SAL,@DEPTNO FROM INSERTED I
		END
	END
END

INSERT INTO EMP_DETAILS_VIEW(EMPNO,ENAME,JOB,DNAME) VALUES(11,'DRAKE','TECH','IT')

SELECT * FROM EMP WHERE ENAME = 'DRAKE'
SELECT * FROM DEPT
select columnproperty(object_id('DEPT'),'DEPTNO','IsIdentity')


-------------------------------------------
-----------dynamic sql---------------------
-------------------------------------------
--1
DECLARE @CITY VARCHAR(20)
SET @CITY = 'NEW YORK'
SELECT * FROM DEPT WHERE LOC = @CITY

--2
DECLARE @SQLCOMMAND VARCHAR(1000)
DECLARE @COLUMNLIST VARCHAR(70)
DECLARE @CITY1 VARCHAR(20)

SET @COLUMNLIST = 'EMPNO,ENAME,JOB,SAL,DEPTNO'
SET @CITY1 = '''BOSTON'''
SET @SQLCOMMAND = 'SELECT '+@COLUMNLIST+' FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC = '+ @CITY1 +' ) '
PRINT @SQLCOMMAND
EXEC (@SQLCOMMAND)

--3

DECLARE @SQLCOMMAND1 NVARCHAR(1000)
DECLARE @COLUMNLIST1 VARCHAR(70)
DECLARE @CITY VARCHAR(20)

SET @COLUMNLIST1 = 'EMPNO,ENAME,JOB,SAL,DEPTNO'
SET @CITY = 'NEW YORK'
SET @SQLCOMMAND1 = 'SELECT '+@COLUMNLIST1+' FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC = @CITY ) '
--PRINT @SQLCOMMAND1

EXECUTE SP_EXECUTESQL @SQLCOMMAND1, N'@CITY NVARCHAR(20)', @CITY = @CITY






